apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name}}
spec:
  kafka:
    version: {{ .Values.kafka.kafka.version}}
    replicas: {{ .Values.kafka.kafka.replicas}}
    listeners:
      - name: plain
        port: {{ .Values.kafka.kafka.listeners.plain.port}}
        type: internal
        tls: false
      - name: tls
        port: {{ .Values.kafka.kafka.listeners.tls.port}}
        type: internal
        tls: true
      - name: external
        port: {{ .Values.kafka.kafka.listeners.external.port}}
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: {{ .Values.kafka.kafka.storage.type}}
      volumes:
      - id: 0
        type: {{ .Values.kafka.kafka.storage.volumes.type}}
        size: {{ .Values.kafka.kafka.storage.volumes.size}}
        deleteClaim: {{ .Values.kafka.kafka.storage.volumes.deleteClaim}}
  zookeeper:
    replicas: {{ .Values.kafka.zookeeper.replicas}}
    storage:
      type: {{ .Values.kafka.zookeeper.storage.type}}
      size: {{ .Values.kafka.zookeeper.storage.size}}
      deleteClaim: {{ .Values.kafka.zookeeper.storage.deleteClaim}}
  entityOperator:
    topicOperator: {}
    userOperator: {}

