apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.dlqueue.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  partitions: {{ .Values.topic.dlqueue.partitions }}
  replicas: {{ .Values.topic.dlqueue.replicas }}
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824